apiVersion: v1
kind: ConfigMap
metadata:
  name: mean-app-config
  namespace: mean-app
data:
  PORT: "8080"
  DB_HOST: "mongodb"
  DB_PORT: "27017"
  DB_NAME: "dd_db"
  DB_URL: "mongodb://mongodb:27017/dd_db"
